---
driver:
  name: vagrant
driver_config:
 require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: manager
    data_bags_path: "test/integration/manager/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/manager/encrypted_data_bag_secret"
    driver:
      network:
      - ["private_network", {ip: "172.16.10.10"}]
    run_list:
      - recipe[wazuh_ossec::manager]
    attributes:
  - name: agent
    driver:
      network:
      - ["private_network", {ip: "172.16.10.11"}]
    run_list:
      - recipe[wazuh_ossec::agent]
    attributes:
