---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: centos-6.7
    run_list: yum::default
suites:
  - name: manager
    data_bags_path: "test/integration/manager/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/manager/encrypted_data_bag_secret"
    run_list:
      - recipe[wazuh_ossec::manager]
    attributes:
  - name: agent
    run_list:
      - recipe[wazuh_ossec::agent]
    attributes:
