---
driver:
  name: vagrant
driver_config:
 require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: manager-development
    environments_path: "test/environments"
    data_bags_path: "test/data_bags"
    encrypted_data_bag_secret_key_path: "test/data_bags/wazuh_secrets/test_data_bag_key"
    driver:
      network:
      - ["private_network", {ip: "172.16.10.10"}]
    run_list:
      - recipe[wazuh_ossec::manager]
    attributes:

  - name: agent-development
    driver:
      network:
      - ["private_network", {ip: "172.16.10.11"}]
    run_list:
      - recipe[wazuh_ossec::agent]
    attributes:
         vagrant:
    provisioner:
      client_rb:
        environment: development
